development:
  adapter: postgresql
  database: book_fellow_development
  pool: 5
  timeout: 5000
  username: username
  password: '12345678'
test:
  adapter: postgresql
  database: book_fellow_test
  pool: 5
  timeout: 5000
production:
  adapter: postgresql
  database: book_fellow_production
  pool: 5
  timeout: 5000